name: Render
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]
jobs:
  deploy:
    name: Wait for Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: rnd_qtIgYInc0kKF4ViJ3odJGlISuBJE
          github-token: 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
          service-id: srv-cm1c8vun7f5s73e6t930
          retries: 20
          wait: 16000
          sleep: 30000
